spring.datasource.url=jdbc:mysql://sql.freedb.tech:3306/freedb_leodata?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=freedb_brnpro
spring.datasource.password=4%A8P!z&q7kY?9%

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=brnprotripz1@gmail.com
spring.mail.password=saiwecpdnrbohakd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true